name: geneext
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.9
  # Compilers (Required so MACS2 can compile itself on any machine)
  - gcc_linux-64
  - gxx_linux-64

  # Core tools
  - bedtools=2.31
  - pybedtools
  - gffutils=0.12
  - samtools=1.19
  - pysam=0.22

  # Data Science & Utils
  - numpy=1.26
  - pandas=2.1
  - scipy=1.13
  - rich=13
  - tqdm
  - pyyaml

  # PIP packages
  - pip
  - pip:
    # Force MACS2 to compile from source (avoids broken binary)
    - MACS2==2.2.9.1 --no-binary MACS2
    - peaks2utr
