name: geneext
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.10
  # Compilers (required for pip-installing macs2)
  - gcc_linux-64
  - gxx_linux-64
  # Core tools
  - bedtools=2.31
  - pybedtools  # <--- Added this (installs pre-compiled, no gcc errors!)
  - gffutils=0.12
  - samtools=1.19
  - pysam=0.22

  # Data Science & Utils
  - numpy=1.26
  - pandas=2.1
  - scipy=1.13       # Added (was in the long list, usually needed if pandas/numpy are there)
  - rich=13
  - tqdm        # Added (was in the pip list, available on conda)
  - pyyaml      # Added for geneext.config

  # PIP packages (Keep this for things not on Conda)
  - pip
  - pip:
    - peaks2utr  # <--- Was in the previous file, likely specific to this project
    - macs2      # <--- Moved to pip to avoid undefined symbol: __log_finite error
