name: geneext
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bedtools
  - gffutils
  - numpy
  - pandas
  - pysam
  - pyyaml
  - rich
  - samtools
  - pip
  - pip:
    - macs2
